import type { TabWithUser, PracticeLogWithUser, User } from "./supabase/types";

// Dummy Users
export const dummyUsers: User[] = [
  {
    id: "user-1",
    clerk_id: "clerk_1",
    username: "guitar_master",
    display_name: "ギターマスター",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=guitar",
    bio: "ギター歴15年。ロック・ブルースが得意です。",
    instruments: ["guitar", "bass"],
    social_links: { twitter: "@guitar_master" },
    plan: "pro",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "user-2",
    clerk_id: "clerk_2",
    username: "bass_groove",
    display_name: "ベースグルーヴ",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=bass",
    bio: "ファンク・ソウル系ベーシスト",
    instruments: ["bass"],
    social_links: null,
    plan: "free",
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "user-3",
    clerk_id: "clerk_3",
    username: "acoustic_soul",
    display_name: "アコースティックソウル",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=acoustic",
    bio: "アコギで弾き語りしてます🎸",
    instruments: ["guitar"],
    social_links: { instagram: "@acoustic_soul" },
    plan: "free",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "user-4",
    clerk_id: "clerk_4",
    username: "metal_shred",
    display_name: "メタルシュレッダー",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=metal",
    bio: "速弾き命！メタル・ハードロック専門",
    instruments: ["guitar"],
    social_links: null,
    plan: "premium",
    created_at: "2024-02-15T00:00:00Z",
    updated_at: "2024-02-15T00:00:00Z",
  },
  {
    id: "user-5",
    clerk_id: "clerk_5",
    username: "jazz_fingers",
    display_name: "ジャズフィンガーズ",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=jazz",
    bio: "ジャズギター研究中。コード理論大好き",
    instruments: ["guitar"],
    social_links: null,
    plan: "pro",
    created_at: "2024-03-01T00:00:00Z",
    updated_at: "2024-03-01T00:00:00Z",
  },
];

// Dummy Tabs
export const dummyTabs: TabWithUser[] = [
  {
    id: "tab-1",
    user_id: "user-1",
    title: "Smoke on the Water",
    artist_name: "Deep Purple",
    tab_data: {},
    difficulty: "beginner",
    genre: "Rock",
    tuning: "Standard",
    instrument: "guitar",
    description: "ロック入門の定番リフ！初心者でも弾けます。",
    thumbnail_url: null,
    is_ai_generated: false,
    is_draft: false,
    is_public: true,
    likes_count: 1234,
    saves_count: 567,
    created_at: "2024-12-01T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z",
    user: dummyUsers[0],
  },
  {
    id: "tab-2",
    user_id: "user-4",
    title: "Master of Puppets",
    artist_name: "Metallica",
    tab_data: {},
    difficulty: "advanced",
    genre: "Metal",
    tuning: "Standard",
    instrument: "guitar",
    description: "メタリカの代表曲。ダウンピッキングの練習に最適。",
    thumbnail_url: null,
    is_ai_generated: false,
    is_draft: false,
    is_public: true,
    likes_count: 2456,
    saves_count: 890,
    created_at: "2024-12-05T14:30:00Z",
    updated_at: "2024-12-05T14:30:00Z",
    user: dummyUsers[3],
  },
  {
    id: "tab-3",
    user_id: "user-3",
    title: "糸",
    artist_name: "中島みゆき",
    tab_data: {},
    difficulty: "intermediate",
    genre: "J-Pop",
    tuning: "Standard",
    instrument: "guitar",
    description: "弾き語りの定番曲。コードチェンジの練習にも。",
    thumbnail_url: null,
    is_ai_generated: true,
    is_draft: false,
    is_public: true,
    likes_count: 876,
    saves_count: 432,
    created_at: "2024-12-10T09:15:00Z",
    updated_at: "2024-12-10T09:15:00Z",
    user: dummyUsers[2],
  },
  {
    id: "tab-4",
    user_id: "user-2",
    title: "Another One Bites the Dust",
    artist_name: "Queen",
    tab_data: {},
    difficulty: "intermediate",
    genre: "Rock",
    tuning: "Standard",
    instrument: "bass",
    description: "超有名ベースライン。グルーヴ感を意識して！",
    thumbnail_url: null,
    is_ai_generated: false,
    is_draft: false,
    is_public: true,
    likes_count: 1567,
    saves_count: 678,
    created_at: "2024-12-12T16:45:00Z",
    updated_at: "2024-12-12T16:45:00Z",
    user: dummyUsers[1],
  },
  {
    id: "tab-5",
    user_id: "user-5",
    title: "Autumn Leaves",
    artist_name: "Jazz Standard",
    tab_data: {},
    difficulty: "advanced",
    genre: "Jazz",
    tuning: "Standard",
    instrument: "guitar",
    description: "ジャズスタンダード。コードメロディとソロ両方収録。",
    thumbnail_url: null,
    is_ai_generated: false,
    is_draft: false,
    is_public: true,
    likes_count: 654,
    saves_count: 321,
    created_at: "2024-12-15T11:20:00Z",
    updated_at: "2024-12-15T11:20:00Z",
    user: dummyUsers[4],
  },
  {
    id: "tab-6",
    user_id: "user-1",
    title: "Hotel California",
    artist_name: "Eagles",
    tab_data: {},
    difficulty: "intermediate",
    genre: "Rock",
    tuning: "Standard",
    instrument: "guitar",
    description: "イントロのアルペジオから有名なツインリードソロまで完全収録。",
    thumbnail_url: null,
    is_ai_generated: true,
    is_draft: false,
    is_public: true,
    likes_count: 3210,
    saves_count: 1456,
    created_at: "2024-12-18T08:00:00Z",
    updated_at: "2024-12-18T08:00:00Z",
    user: dummyUsers[0],
  },
  {
    id: "tab-7",
    user_id: "user-4",
    title: "Eruption",
    artist_name: "Van Halen",
    tab_data: {},
    difficulty: "advanced",
    genre: "Rock",
    tuning: "Standard",
    instrument: "guitar",
    description: "タッピングの教科書。エディの伝説的ソロ。",
    thumbnail_url: null,
    is_ai_generated: false,
    is_draft: false,
    is_public: true,
    likes_count: 1890,
    saves_count: 765,
    created_at: "2024-12-20T13:30:00Z",
    updated_at: "2024-12-20T13:30:00Z",
    user: dummyUsers[3],
  },
  {
    id: "tab-8",
    user_id: "user-3",
    title: "チェリー",
    artist_name: "スピッツ",
    tab_data: {},
    difficulty: "beginner",
    genre: "J-Pop",
    tuning: "Standard",
    instrument: "guitar",
    description: "初心者向けの弾き語り曲。基本コードだけで弾けます。",
    thumbnail_url: null,
    is_ai_generated: false,
    is_draft: false,
    is_public: true,
    likes_count: 2100,
    saves_count: 980,
    created_at: "2024-12-22T10:00:00Z",
    updated_at: "2024-12-22T10:00:00Z",
    user: dummyUsers[2],
  },
];

// Dummy Practice Logs
export const dummyPracticeLogs: PracticeLogWithUser[] = [
  {
    id: "log-1",
    user_id: "user-1",
    tab_id: "tab-1",
    content: "Smoke on the Waterのリフを30分練習。だいぶスムーズに弾けるようになってきた！明日はテンポを上げてみよう。",
    practice_duration: 30,
    media_url: null,
    is_public: true,
    likes_count: 45,
    created_at: "2024-12-23T18:00:00Z",
    updated_at: "2024-12-23T18:00:00Z",
    user: dummyUsers[0],
    tab: dummyTabs[0],
  },
  {
    id: "log-2",
    user_id: "user-4",
    tab_id: "tab-2",
    content: "Master of Puppetsのダウンピッキング地獄...右手が死にそう😂 でも少しずつ持久力ついてきた気がする。",
    practice_duration: 60,
    media_url: null,
    is_public: true,
    likes_count: 89,
    created_at: "2024-12-23T20:30:00Z",
    updated_at: "2024-12-23T20:30:00Z",
    user: dummyUsers[3],
    tab: dummyTabs[1],
  },
  {
    id: "log-3",
    user_id: "user-3",
    tab_id: null,
    content: "今日はコードチェンジの練習を重点的に。G→C→D→Emの流れがだいぶ自然になってきた🎸",
    practice_duration: 45,
    media_url: null,
    is_public: true,
    likes_count: 23,
    created_at: "2024-12-24T09:00:00Z",
    updated_at: "2024-12-24T09:00:00Z",
    user: dummyUsers[2],
    tab: null,
  },
  {
    id: "log-4",
    user_id: "user-2",
    tab_id: "tab-4",
    content: "Another One Bites the Dustのベースライン完コピ達成！🎉 グルーヴ感を出すのが難しかったけど、メトロノームと格闘した甲斐があった。",
    practice_duration: 90,
    media_url: null,
    is_public: true,
    likes_count: 156,
    created_at: "2024-12-24T15:00:00Z",
    updated_at: "2024-12-24T15:00:00Z",
    user: dummyUsers[1],
    tab: dummyTabs[3],
  },
  {
    id: "log-5",
    user_id: "user-5",
    tab_id: "tab-5",
    content: "Autumn Leavesのコードメロディを研究中。ボイシングの選び方で全然雰囲気変わるなぁ。ジャズ深い...",
    practice_duration: 120,
    media_url: null,
    is_public: true,
    likes_count: 67,
    created_at: "2024-12-24T21:00:00Z",
    updated_at: "2024-12-24T21:00:00Z",
    user: dummyUsers[4],
    tab: dummyTabs[4],
  },
];

// Helper functions
export function getTabById(id: string): TabWithUser | undefined {
  return dummyTabs.find((tab) => tab.id === id);
}

export function getUserByUsername(username: string): User | undefined {
  return dummyUsers.find((user) => user.username === username);
}

export function getTabsByUserId(userId: string): TabWithUser[] {
  return dummyTabs.filter((tab) => tab.user_id === userId);
}

export function getPracticeLogsByUserId(userId: string): PracticeLogWithUser[] {
  return dummyPracticeLogs.filter((log) => log.user_id === userId);
}

export function getTrendingTabs(): TabWithUser[] {
  return [...dummyTabs].sort((a, b) => b.likes_count - a.likes_count);
}

export function getRecentTabs(): TabWithUser[] {
  return [...dummyTabs].sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  );
}

export function getTimelinePosts(): (TabWithUser | PracticeLogWithUser)[] {
  const allPosts = [
    ...dummyTabs.map((tab) => ({ ...tab, type: "tab" as const })),
    ...dummyPracticeLogs.map((log) => ({ ...log, type: "practice_log" as const })),
  ];
  return allPosts.sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  );
}


